version: '3.3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./nginx/conf.d:/etc/nginx/conf.d"

  api_server:
    image: node:8.9.4-alpine
    volumes:
      - "./api_server:/src"
    working_dir: /src
    command: [sh, -c, yarn install && yarn start]
    ports:
      - "3000:3000"

  mysql:
    image: mysql:5.7
    volumes:
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf # 設定ファイル投入
      - ./mysql/mysql_data:/var/lib/mysql # データの永続化
      - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期データ投入
    ports:
      - "3306:3306"
    command: [mysqld]
    environment:
      - "MYSQL_ROOT_PASSWORD=root"